version: "3"

services:
  traefik:
    image: traefik
    container_name: traefik
    labels:
      - "traefik.frontend.rule=Host:traefik.dock"
      - "traefik.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./conf/traefik.toml:/traefik.toml"
    ports:
      - "80:80"
      - "443:443"
    networks:
      server:
        aliases:
          - "core.towl.fr"

networks:
  server:
    external: true
